export const ApiUrls = {
  auth: {
    AUTH: "/auth",
  },
  participants: {
    LIST: "/Participants",
    DETAILS: (id: number) => `/Participants/${id}`,
    WITH_ENROLLMENTS: (id: number) => `/Participants/${id}/enrollments`,
    SEARCH: "/Participants/search",
  },
  trainings: {
    LIST: "/TrainingPrograms",
    DETAILS: (id: number) => `/TrainingPrograms/${id}`,
    WITH_PARTICIPANTS: (id: number) => `/TrainingPrograms/${id}/participants`,
    SEARCH: "/TrainingPrograms",
    ACTIVE: "/TrainingPrograms/active",
    BY_FINANCIAL_YEAR: (financialYear: string) => `/TrainingPrograms/financial-year/${financialYear}`,
  },
  enrollment: {
    LIST: "/TrainingEnrollment",
    BY_ID: (id: number) => `/TrainingEnrollment/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/TrainingEnrollment/participant/${participantId}`,
    BY_TRAINING: (trainingId: number) => `/TrainingEnrollment/training/${trainingId}`,
    CREATE: "/TrainingEnrollment",
    UPDATE: (id: number) => `/TrainingEnrollment/${id}`,
    DELETE: (id: number) => `/TrainingEnrollment/${id}`,
  },
  lookup: {
    DEPARTMENTS: "/Lookup/departments",
    FACILITIES: "/Lookup/facilities",
    DESIGNATIONS: "/Lookup/designations",
    SALARY_SCALES: "/Lookup/salary-scales",
    SPONSORS: "/Lookup/sponsors",
    ALLOWANCE_TYPES: "/Lookup/allowance-types",
    ALLOWANCE_STATUSES: "/Lookup/allowance-statuses",
    ALL: "/Lookup/all",
  },
  allowanceTypes: {
    LIST: "/AllowanceTypes",
    DETAILS: (id: number) => `/AllowanceTypes/${id}`,
    CREATE: "/AllowanceTypes",
    UPDATE: (id: number) => `/AllowanceTypes/${id}`,
    DELETE: (id: number) => `/AllowanceTypes/${id}`,
    LOOKUP: "/AllowanceTypes/lookup",
  },
  allowanceStatuses: {
    LIST: "/AllowanceStatuses",
    DETAILS: (id: number) => `/AllowanceStatuses/${id}`,
    CREATE: "/AllowanceStatuses",
    UPDATE: (id: number) => `/AllowanceStatuses/${id}`,
    DELETE: (id: number) => `/AllowanceStatuses/${id}`,
    LOOKUP: "/AllowanceStatuses/lookup",
  },
  allowances: {
    LIST: "/Allowances",
    DETAILS: (id: number) => `/Allowances/${id}`,
    CREATE: "/Allowances",
    UPDATE: (id: number) => `/Allowances/${id}`,
    DELETE: (id: number) => `/Allowances/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/Allowances/participant/${participantId}`,
    BY_TRAINING: (trainingId: number) => `/Allowances/training/${trainingId}`,
    BY_STATUS: (statusId: number) => `/Allowances/status/${statusId}`,
    BY_TYPE: (typeId: number) => `/Allowances/type/${typeId}`,
    DATE_RANGE: "/Allowances/date-range",
    TOTAL_BY_PARTICIPANT: (participantId: number) => `/Allowances/participant/${participantId}/total`,
  },
  nomination: {
    START: "/enrollment-wizard/start",
    GET_PROGRESS_BY_PARTICIPANT: (participantId: number) => `/enrollment-wizard/progress/${participantId}`,
    GET_PROGRESS_BY_ID: (progressId: number) => `/enrollment-wizard/progress/id/${progressId}`,
    UPDATE_STEP: (progressId: number, step: number) => `/enrollment-wizard/progress/${progressId}/step/${step}`,
    SAVE_PROGRESS: (progressId: number) => `/enrollment-wizard/progress/${progressId}/save`,
    SAVE_FORM2: (progressId: number) => `/enrollment-wizard/progress/${progressId}/form2/save`,
    GET_FORM2: (progressId: number) => `/enrollment-wizard/progress/${progressId}/form2`,
    CANCEL: (progressId: number) => `/enrollment-wizard/progress/${progressId}/cancel`,
    RESUME: (progressId: number, step: number) => `/enrollment-wizard/progress/${progressId}/resume/${step}`,
    IN_PROGRESS: "/enrollment-wizard/in-progress",
    STATISTICS: "/enrollment-wizard/statistics",
  },
};