export const ApiUrls = {
  auth: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    PROFILE: "/auth/profile",
    CHANGE_PASSWORD: "/auth/change-password",
    LOGOUT: "/auth/logout",
    VALIDATE_TOKEN: "/auth/validate-token",
  },
  participants: {
    LIST: "/participants",
    DETAILS: (id: number) => `/participants/${id}`,
    NEXT_OF_KIN: (id: number) => `/participants/${id}/next-of-kin`,
  },
  nominations: {
    LIST: "/nominations",
    DETAILS: (id: number) => `/nominations/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/nominations/participant/${participantId}`,
  },
  admissions: {
    LIST: "/admissions",
    DETAILS: (id: number) => `/admissions/${id}`,
    BY_NOMINATION: (nominationId: number) => `/admissions/nomination/${nominationId}`,
  },
  allowances: {
    LIST: "/allowances",
    DETAILS: (id: number) => `/allowances/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/allowances/participant/${participantId}`,
    BY_ADMISSION: (admissionId: number) => `/allowances/admission/${admissionId}`,
  },
  allowanceTypes: {
    LIST: "/allowance-types",
    DETAILS: (id: number) => `/allowance-types/${id}`,
  },
  allowanceStatuses: {
    LIST: "/allowance-statuses",
    DETAILS: (id: number) => `/allowance-statuses/${id}`,
  },
  lookups: {
    ALL: "/lookups/all",
    TITLES: "/lookups/titles",
    TITLE: (id: number) => `/lookups/titles/${id}`,
    ID_TYPES: "/lookups/id-types",
    ID_TYPE: (id: number) => `/lookups/id-types/${id}`,
    RELATIONSHIP_TYPES: "/lookups/relationship-types",
    RELATIONSHIP_TYPE: (id: number) => `/lookups/relationship-types/${id}`,
    DEPARTMENTS: "/lookups/departments",
    DEPARTMENT: (id: number) => `/lookups/departments/${id}`,
    SALARY_SCALES: "/lookups/salary-scales",
    SALARY_SCALE: (id: number) => `/lookups/salary-scales/${id}`,
    DUTY_STATIONS: "/lookups/duty-stations",
    DUTY_STATION: (id: number) => `/lookups/duty-stations/${id}`,
    SPONSOR_TYPES: "/lookups/sponsor-types",
    SPONSOR_TYPE: (id: number) => `/lookups/sponsor-types/${id}`,
    QUALIFICATIONS: "/lookups/qualifications",
    QUALIFICATION: (id: number) => `/lookups/qualifications/${id}`,
    NOMINATED_PROGRAMS: "/lookups/nominated-programs",
    NOMINATED_PROGRAM: (id: number) => `/lookups/nominated-programs/${id}`,
    ADMISSION_PROGRAMS: "/lookups/admission-programs",
    ADMISSION_PROGRAM: (id: number) => `/lookups/admission-programs/${id}`,
    MODES_OF_STUDY: "/lookups/modes-of-study",
    MODE_OF_STUDY: (id: number) => `/lookups/modes-of-study/${id}`,
  },
};