export const ApiUrls = {
  auth: {
    AUTH: "/auth",
  },
  participants: {
    LIST: "/Participants",
    DETAILS: (id: number) => `/Participants/${id}`,
    WITH_ENROLLMENTS: (id: number) => `/Participants/${id}/enrollments`,
    SEARCH: "/Participants/search",
  },
  trainings: {
    LIST: "/Trainings",
    DETAILS: (id: number) => `/Trainings/${id}`,
    WITH_PARTICIPANTS: (id: number) => `/Trainings/${id}/participants`,
    SEARCH: "/Trainings/search",
    ACTIVE: "/Trainings/active",
    BY_FINANCIAL_YEAR: (financialYear: string) => `/Trainings/financial-year/${financialYear}`,
  },
  enrollment: {
    LIST: "/TrainingEnrollment",
    BY_ID: (id: number) => `/TrainingEnrollment/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/TrainingEnrollment/participant/${participantId}`,
    BY_TRAINING: (trainingId: number) => `/TrainingEnrollment/training/${trainingId}`,
    CREATE: "/TrainingEnrollment",
    UPDATE: (id: number) => `/TrainingEnrollment/${id}`,
    DELETE: (id: number) => `/TrainingEnrollment/${id}`,
  },
  lookup: {
    DEPARTMENTS: "/Lookup/departments",
    FACILITIES: "/Lookup/facilities",
    DESIGNATIONS: "/Lookup/designations",
    SALARY_SCALES: "/Lookup/salary-scales",
    SPONSORS: "/Lookup/sponsors",
    ALLOWANCE_TYPES: "/Lookup/allowance-types",
    ALLOWANCE_STATUSES: "/Lookup/allowance-statuses",
    ALL: "/Lookup/all",
  },
  allowanceTypes: {
    LIST: "/AllowanceTypes",
    DETAILS: (id: number) => `/AllowanceTypes/${id}`,
    CREATE: "/AllowanceTypes",
    UPDATE: (id: number) => `/AllowanceTypes/${id}`,
    DELETE: (id: number) => `/AllowanceTypes/${id}`,
    LOOKUP: "/AllowanceTypes/lookup",
  },
  allowanceStatuses: {
    LIST: "/AllowanceStatuses",
    DETAILS: (id: number) => `/AllowanceStatuses/${id}`,
    CREATE: "/AllowanceStatuses",
    UPDATE: (id: number) => `/AllowanceStatuses/${id}`,
    DELETE: (id: number) => `/AllowanceStatuses/${id}`,
    LOOKUP: "/AllowanceStatuses/lookup",
  },
  allowances: {
    LIST: "/Allowances",
    DETAILS: (id: number) => `/Allowances/${id}`,
    CREATE: "/Allowances",
    UPDATE: (id: number) => `/Allowances/${id}`,
    DELETE: (id: number) => `/Allowances/${id}`,
    BY_PARTICIPANT: (participantId: number) => `/Allowances/participant/${participantId}`,
    BY_TRAINING: (trainingId: number) => `/Allowances/training/${trainingId}`,
    BY_STATUS: (statusId: number) => `/Allowances/status/${statusId}`,
    BY_TYPE: (typeId: number) => `/Allowances/type/${typeId}`,
    DATE_RANGE: "/Allowances/date-range",
    TOTAL_BY_PARTICIPANT: (participantId: number) => `/Allowances/participant/${participantId}/total`,
  },
};